api_version = '2'
provider    = 'virtualbox'
box         = 'ubuntu/trusty64'
url         = 'https://vagrantcloud.com/ubuntu/boxes/trusty64'
hostname    = 'dvwa'
ip          = '192.168.50.12'
ram         = '2048'
cpus        = '2'

Vagrant.configure(api_version) do |config|
    config.vm.define "dvwa" do |dvwa|
    end

    config.vm.box = box
    config.vm.box_url = url
    config.vm.host_name = hostname
    config.vm.network :private_network, ip: ip
    
    config.vm.provider :virtualbox do |virtualbox|
        virtualbox.name = hostname
        virtualbox.memory = ram
        virtualbox.cpus = cpus
        virtualbox.customize ['modifyvm', :id, '--name', hostname]
    end

    config.vm.provision "shell" do |setup|
        setup.path = "provision/vagrant.sh"
        setup.privileged = true
    end

end
