api_version = '2'
provider    = 'virtualbox'
box         = 'ubuntu/trusty64'
url         = 'https://vagrantcloud.com/ubuntu/boxes/trusty64'
hostname    = 'ec-azure-experimental'
ip          = '192.168.50.10'
ram         = '2048'

Vagrant.configure(api_version) do |config|
    config.vm.box = box
    config.vm.box_url = url
    config.vm.host_name = hostname
    config.vm.network :private_network, ip: ip
    
    config.vm.provision "shell" do |setup|
        setup.path = "provision/vagrant.sh"
        setup.privileged = true
    end

    config.vm.provision "shell" do |config|
        config.path = "provision/ec-setup.sh"
        config.privileged = false
    end

    config.vm.provider :virtualbox do |virtualbox|
        virtualbox.name = hostname
        virtualbox.customize ['modifyvm', :id, '--name', hostname]
        virtualbox.customize ['modifyvm', :id, '--memory', ram]
    end
end
