api_version = '2'
provider    = 'virtualbox'
box         = 'hashicorp/precise64'
hostname    = 'ngix'
ip          = '192.168.50.13'
ram         = '2048'
cpus        = '2'

Vagrant.configure(api_version) do |config|
    config.vm.define "ngix" do |ngix|
    end

    config.vm.box = box
    config.vm.host_name = hostname
    config.vm.network :private_network, ip: ip
    
    config.vm.provider :virtualbox do |virtualbox|
        virtualbox.name = hostname
        virtualbox.memory = ram
        virtualbox.cpus = cpus
        virtualbox.customize ['modifyvm', :id, '--name', hostname]
    end

    config.vm.provision "shell" do |setup|
        setup.path = "provision/vagrant.sh"
        setup.privileged = true
    end

    config.vm.provision "shell" ,run: "always" do |setup|
        setup.path = "provision/nginx.sh"
        setup.privileged = true
    end
end
